sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fmbVFNDsse+D7meDo+Nnu8tUnpaqil6uDAlfCWlNgrrJuGHo/voE8HLUG6/ZMtcndLCfJJ3264f/z6azITp55HvZbWnSBgDAhkG/taGk/KF6i2B4Nrwyhuhn46tBek65cosqs1FTzaF4GsCGZwIK39hf4EgGyFoTBmD8UOOyxI/G907hDxXllF5zJywDXotrjk74AupvFOI/ZxS21jX5qzIW4iO+M/+lnCb1q1+F0TnIFK8VbIdBCZrQxAnBSo6pjLM7NuzXR4GCVpA/BMw60RtVkYSLlmJ8YQAoNkuXzvI4K/K1kWyfK608RUNEXJwC+UaVahky+KPMwWnq/hEps6gsnhPpQSyNSglPcTLNSZh7QYramL8fSmsWjJDlZsbfJZJVW2s9jwDHcGedfCE1jLJBRzXR4iBbIAI5mLfl3h2m5+1U8HQ6A9NZmfriRcAL6jDp+U00YPRxZMKIMLqNEmV2dtydvveFZYax/xynu4f2JrCV3QcneZ5FinGq0/5YgjtF9AG05oPKKrGc9ExnZhmDQIeBDWOL87ud3eoxCdcPcJ8/8ZOMvAIFL6je55GbzJXuLnbcLyDUmkjNlSW3BwjNv/kcFzaKAlYGrYFuOyTo8//s5fRRZaSUZF123rLFLorPpSn6yDtuwsKOztaYSAtjIfOo3y4GGAPeFsqZoQs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Works-of-John-Bunyan-Volume-01_6046
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy